=== jiangxiaolhm/wsd/web/WEB-INF/listings.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://learn.it.uts.edu.au/wsd"
           xmlns="http://learn.it.uts.edu.au/wsd"
           elementFormDefault="qualified">
    
    <xs:element name="listings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="listing" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="listingID" type="xs:integer"/>
                            <xs:element name="user">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="userID" type="xs:integer"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="email" type="email"/>
                                        <xs:element name="DOB" type="DOB"/>
                                        <xs:element name="password" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="flight" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flightID" type="xs:string"/>
                                        <xs:element name="dDateTime" type="dDateTime"/>
                                        <xs:element name="rDateTime" type="rDateTime"/>
                                        <xs:element name="type" type="xs:string"/>
                                        <xs:element name="price" type="xs:double"/>
                                        <xs:element name="numOfSeats" type="xs:integer"/>
                                        <xs:element name="from" type="xs:string"/>
                                        <xs:element name="to" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="description" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DOB">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dDateTime">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}\s([0-1][0-9]|2[0-3])\:[0-5][0-9]\:[0-5][0-9]" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="rDateTime">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}\s([0-1][0-9]|2[0-3])\:[0-5][0-9]\:[0-5][0-9]" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== jiangxiaolhm/wsd/web/WEB-INF/listings.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="listings.xsl"?>
<a:listings xmlns:a="http://learn.it.uts.edu.au/wsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://learn.it.uts.edu.au/wsd listings.xsd">
    
    <a:listing>
        <a:listingID>123</a:listingID>
        <a:user>
            <a:userID>123456</a:userID>
            <a:name>XiRanLi</a:name>
            <a:email>lixiranph@126.com</a:email>
            <a:DOB>30/10/1994</a:DOB>
            <a:password>A123123</a:password>
            <a:type>Customer</a:type>
        </a:user>
        <a:flight>
            <a:flightID>AU177</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:flight>
            <a:flightID>AU172</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:description>Active</a:description>
    </a:listing>
    <a:listing>
        <a:listingID>3435</a:listingID>
        <a:user>
            <a:userID>123456</a:userID>
            <a:name>XiRanLi</a:name>
            <a:email>lixiranph@126.com</a:email>
            <a:DOB>30/10/1994</a:DOB>
            <a:password>A123123</a:password>
            <a:type>Customer</a:type>
        </a:user>
        <a:flight>
            <a:flightID>AU177</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:description>Active</a:description>
    </a:listing>
    <a:listing>
        <a:listingID>223</a:listingID>
        <a:user>
            <a:userID>123456</a:userID>
            <a:name>XiRanLi</a:name>
            <a:email>lixiranph@126.com</a:email>
            <a:DOB>30/10/1994</a:DOB>
            <a:password>A123123</a:password>
            <a:type>Customer</a:type>
        </a:user>
        <a:flight>
            <a:flightID>AU177</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:description>Active</a:description>
    </a:listing>
    <a:listing>
        <a:listingID>3745</a:listingID>
        <a:user>
            <a:userID>123456</a:userID>
            <a:name>XiRanLi</a:name>
            <a:email>lixiranph@126.com</a:email>
            <a:DOB>30/10/1994</a:DOB>
            <a:password>A123123</a:password>
            <a:type>Customer</a:type>
        </a:user>
        <a:flight>
            <a:flightID>AU177</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:description>Active</a:description>
    </a:listing>
    <a:listing>
        <a:listingID>775</a:listingID>
        <a:user>
            <a:userID>123456</a:userID>
            <a:name>XiRanLi</a:name>
            <a:email>lixiranph@126.com</a:email>
            <a:DOB>30/10/1994</a:DOB>
            <a:password>A123123</a:password>
            <a:type>Customer</a:type>
        </a:user>
        <a:flight>
            <a:flightID>AU177</a:flightID>
            <a:dDateTime>19/06/2017 18:00:00</a:dDateTime>
            <a:rDateTime>20/06/2017 20:30:00</a:rDateTime>
            <a:type>Economy</a:type>
            <a:price>99.99</a:price>
            <a:numOfSeats>100</a:numOfSeats>
            <a:from>Sydney</a:from>
            <a:to>Melbourne</a:to>
        </a:flight>
        <a:description>Active</a:description>
    </a:listing>
</a:listings>
